<a href="https://colab.research.google.com/github/ChrisM1101/PyTorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.cuda.is_available()) # will return True if PyTorch can use the GPU
print(torch.__version__)

False
2.5.1+cu121


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using  'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [11]:
scalar.shape

torch.Size([])

In [4]:
# Get tensor back as python int
scalar.item()

7

In [8]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX
MATRIX = torch.tensor([[5, 6],
                       [7, 8]])
MATRIX

tensor([[5, 6],
        [7, 8]])

In [17]:
MATRIX.ndim

2

In [20]:
MATRIX[1]

tensor([7, 8])

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [25]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [26]:
TENSOR.ndim

3

In [27]:
TENSOR.shape

torch.Size([1, 3, 3])

In [36]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
TENSOR2 = torch.tensor([[[[[1, 2, 3, 4, 5, 6],
            [7, 8, 9, 10, 11, 12],
             [13, 14, 15, 16, 17, 18],
             [19, 20, 21, 22, 23, 24]],
            [[11, 22, 33, 44, 55, 66],
             [111, 222, 333, 444, 555, 666],
             [1111, 2222, 3333, 4444, 5555, 6666],
             [11111, 22222, 33333, 44444, 55555, 66666]],
            [[0, 0, 0, 0, 0, 0],
             [77, 88, 99, 00, 11, 22],
             [777, 888, 999, 000, 111, 222],
             [7777, 8888, 9999, 0000, 1111, 2222]]]]])
TENSOR2

tensor([[[[[    1,     2,     3,     4,     5,     6],
           [    7,     8,     9,    10,    11,    12],
           [   13,    14,    15,    16,    17,    18],
           [   19,    20,    21,    22,    23,    24]],

          [[   11,    22,    33,    44,    55,    66],
           [  111,   222,   333,   444,   555,   666],
           [ 1111,  2222,  3333,  4444,  5555,  6666],
           [11111, 22222, 33333, 44444, 55555, 66666]],

          [[    0,     0,     0,     0,     0,     0],
           [   77,    88,    99,     0,    11,    22],
           [  777,   888,   999,     0,   111,   222],
           [ 7777,  8888,  9999,     0,  1111,  2222]]]]])

In [52]:
TENSOR2.ndim

5

In [53]:
TENSOR2.shape

torch.Size([1, 1, 3, 4, 6])

In [64]:
TENSOR2[0][0][1][3][2]

tensor(33333)