<a href="https://colab.research.google.com/github/ChrisM1101/PyTorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.cuda.is_available()) # will return True if PyTorch can use the GPU
print(torch.__version__)

False
2.5.1+cu121


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using  'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
# Get tensor back as python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[5, 6],
                       [7, 8]])
MATRIX

tensor([[5, 6],
        [7, 8]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR2 = torch.tensor([[[[[1, 2, 3, 4, 5, 6],
            [7, 8, 9, 10, 11, 12],
             [13, 14, 15, 16, 17, 18],
             [19, 20, 21, 22, 23, 24]],
            [[11, 22, 33, 44, 55, 66],
             [111, 222, 333, 444, 555, 666],
             [1111, 2222, 3333, 4444, 5555, 6666],
             [11111, 22222, 33333, 44444, 55555, 66666]],
            [[0, 0, 0, 0, 0, 0],
             [77, 88, 99, 00, 11, 22],
             [777, 888, 999, 000, 111, 222],
             [7777, 8888, 9999, 0000, 1111, 2222]]]]])
TENSOR2

tensor([[[[[    1,     2,     3,     4,     5,     6],
           [    7,     8,     9,    10,    11,    12],
           [   13,    14,    15,    16,    17,    18],
           [   19,    20,    21,    22,    23,    24]],

          [[   11,    22,    33,    44,    55,    66],
           [  111,   222,   333,   444,   555,   666],
           [ 1111,  2222,  3333,  4444,  5555,  6666],
           [11111, 22222, 33333, 44444, 55555, 66666]],

          [[    0,     0,     0,     0,     0,     0],
           [   77,    88,    99,     0,    11,    22],
           [  777,   888,   999,     0,   111,   222],
           [ 7777,  8888,  9999,     0,  1111,  2222]]]]])

In [18]:
TENSOR2.ndim

5

In [19]:
TENSOR2.shape

torch.Size([1, 1, 3, 4, 6])

In [20]:
TENSOR2[0][0][1][3][2]

tensor(33333)

### RANDOM TENSORS

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> Look at data -> Update random numbers -> Look at data -> Update random numbers`

Torch random tensors: https://pytorch.org/docs/main/generated/torch.rand.html

In [21]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4147, 0.5747, 0.1589, 0.9398],
        [0.7189, 0.0203, 0.7513, 0.9991],
        [0.0724, 0.1693, 0.8489, 0.1393]])

In [22]:
random_tensor.ndim

2

In [23]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
random_tensor.dtype

torch.float32

In [28]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [29]:
# Use torch.range() and get deprecated message, use torch.arange() instead
torch.range(0, 10)

<ipython-input-29-16053d63d4b2>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
torch.__version__

'2.5.1+cu121'

In [31]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
one_to_thousand = torch.arange(start=1, end=1000, step=77)
one_to_thousand

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [33]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you''ll run into with PyTorch and Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [34]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether of not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [35]:
float_32_tensor.dtype

torch.float32

In [36]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [38]:
int_64_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_64_tensor

tensor([3, 6, 9])

In [39]:
float_32_tensor * int_64_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [40]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2102, 0.6266, 0.8044, 0.6705],
        [0.1722, 0.3963, 0.5669, 0.7065],
        [0.1708, 0.7901, 0.1635, 0.3341]])

In [43]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.2102, 0.6266, 0.8044, 0.6705],
        [0.1722, 0.3963, 0.5669, 0.7065],
        [0.1708, 0.7901, 0.1635, 0.3341]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors

Tension operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [44]:
# Create a tensor ad add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [45]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [46]:
# Subtract 10
tensor-10

tensor([-9, -8, -7])

In [47]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [48]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shapeof the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [78]:
torch.matmul(torch.rand(11, 11), torch.rand(11, 11)).shape

torch.Size([11, 11])

In [70]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [52]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [53]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [60]:
tensor @ tensor

tensor(14)

In [57]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 2.86 ms, sys: 0 ns, total: 2.86 ms
Wall time: 2.68 ms


In [58]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 76 µs, sys: 5 µs, total: 81 µs
Wall time: 87.5 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [80]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [81]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [86]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [88]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [93]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
